namespace ReportBuilderAjax.Web
{
    public enum ReportEnum
    {
        UnknownReport = 1,
        CheckRegister = 1011,
        TransactionRegister = 1012,
        LossRunSummary = 1014,
        ManagedCareSavingsAndFees = 1015,
        AggregateReportDetailPaid = 1016,
        ManagedCareSavingsAndFeesDetail = 1017,
        MonthlyBillingReport = 1018,
        AggregateReportSummaryPaid = 1019,
        ManagedCareSavingsByState = 1021,
        LossRatioWithLossSummary = 1022,
        ManagedCareBillsAndChargesByProvider = 1023,
        ManagedCareSavingsByProviderType = 1024,
        LossRunDetailExpanded = 1025,
        StewardshipReport = 1028,
        ManagedCarePharmacyPBMSavings = 1027,
        AggregateReportDetailIncurred = 1029,
        AggregateReportSummaryIncurred = 1030,
        SIRDeductibleSpecificDetailIncurred = 1031,
        SIRDeductibleSpecificDetailPaid = 1032,
        SIRDeductibleSpecificSummaryIncurred = 1033,
        SIRDeductibleSpecificSummaryPaid = 1034,
        ClaimLag = 1026,
        ActivityReport = 1035,
        ReserveChangeReport = 1036,
        ManagedCareDiagnosticSavings = 1040,
        LossRunSummaryWithCurrentPaid = 1041,
        LitigationManagementBasic = 1045,
        LitigationManagementDetail = 1046,
        ClosingRatio = 1042,
        PAndIReimbursableReport = 1043,
        NoteAnalysis = 1044,
        LossSummaryByCoverageAndPaymentClass = 1047,
        ComparisonReport = 1048,
        CorridorDeductible = 1049,
        SummaryLossByClassEmplyeeInjury = 1050,
        MadicareQueryFucntion = 1051,
        CFPEndorsementIncurredDetail = 1054,
        CFPEndorsementIncurredSummary = 1055,
        CFPEndorsementPaidDetail = 1056,
        CFPEndorsementPaidSummary = 1057,
        LossRunSummaryForPowerUser = 1058
    }
}
